"""Build every generated artifact from data/: build/*.json, web/data.js, docs/scene-notes.md.
Refuses to build when validation fails."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from ff_magic.aggregate import SCOPES, character_totals, event_totals, film_totals, screen_time  # noqa: E402
from ff_magic.dataset import load_dataset  # noqa: E402
from ff_magic.magic import odds_label  # noqa: E402
from ff_magic.montecarlo import simulate  # noqa: E402
from ff_magic.render_docs import scene_notes  # noqa: E402
from ff_magic.validate import validate  # noqa: E402


def dump(path: Path, obj):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=1, sort_keys=True, ensure_ascii=False) + "\n")


def build(data_dir: Path, out_dir: Path, web_js: Path | None, notes: Path | None) -> dict:
    ds = load_dataset(data_dir)
    rep = validate(ds)
    if rep.failures:
        raise SystemExit("refusing to build; validation failed:\n" + "\n".join(rep.failures))
    events = {e.id: (fid, e) for fid, e in ds.events}
    detail = {}
    for eid, (fid, e) in events.items():
        d = e.model_dump()
        d["film"] = fid
        for c in d["components"]:
            c["odds"] = odds_label(c["mu"]["central"], lower_bound=c["capped"])
        detail[eid] = d
    site = {
        "config": ds.config.model_dump(),
        "films": [f.model_dump() for f in ds.films],
        "characters": {c.id: c.model_dump() for c in ds.characters},
        "sources": {s.id: s.model_dump() for s in ds.sources},
        "references": {r.id: r.model_dump() for r in ds.references},
        "events": detail,
        "plot_armor": [p.model_dump() for p in ds.plot_armor],
        "rejected": [x.model_dump() for x in ds.rejected],
        "scopes": {},
    }
    for scope in SCOPES:
        ev = event_totals(ds, scope)
        for e in ev:
            e["odds"] = odds_label(e["central"], lower_bound=e["lower_bound"])
            e["odds_low"] = odds_label(e["low"], lower_bound=e["lower_bound"])
            e["odds_high"] = odds_label(e["high"], lower_bound=e["lower_bound"])
        mc = simulate(ds, scope)
        site["scopes"][scope] = {
            "scenes": ev,
            "characters": character_totals(ds, scope),
            "films": film_totals(ds, scope),
            "screen_time": screen_time(ds, scope),
            "rank_stability": mc,
        }
        for name in ("scenes", "characters", "films"):
            dump(out_dir / scope / f"{name}.json", site["scopes"][scope][name])
        dump(out_dir / scope / "rank_stability.json", mc)
    dump(out_dir / "site.json", site)
    if web_js is not None:
        web_js.write_text("// GENERATED by scripts/build.py from data/. Do not edit.\nwindow.FF_DATA = "
                          + json.dumps(site, sort_keys=True, ensure_ascii=False) + ";\n")
    if notes is not None:
        notes.write_text(scene_notes(site))
    return {"events": len(ds.events), "checks": rep.n_checks}


if __name__ == "__main__":
    info = build(ROOT / "data", ROOT / "build", ROOT / "web" / "data.js", ROOT / "docs" / "scene-notes.md")
    print(f"built: {info['events']} events; validation {info['checks']} checks passed")
