/* Every figure on this page is read from window.FF_DATA (generated by scripts/build.py from data/).
   Nothing is hand-typed: tests/test_web_numbers.py fails if a number in the DOM is not in the JSON. */
(function () {
  const D = window.FF_DATA;
  const CATS = ["physics", "survival", "skill", "coincidence"];
  const CATCOLOR = {
    physics: "var(--ffmu-data-physics)",
    survival: "var(--ffmu-data-survival)",
    skill: "var(--ffmu-data-skill)",
    coincidence: "var(--ffmu-data-coincidence)",
  };
  const EVIDENCE = {
    E1: "empirical frequency",
    E2: "physics model",
    E3: "geometry or timing",
    E4: "judgment prior",
  };
  const el = (tag, cls, text) => {
    const n = document.createElement(tag);
    if (cls) n.className = cls;
    if (text !== undefined) n.textContent = text;
    return n;
  };
  const fmt = (x) => (Math.round(x * 10) / 10).toString();
  const mu = (v, lower) => (lower ? "≥" : "") + fmt(v);
  const filmById = {};
  D.films.forEach((f) => (filmById[f.id] = f));
  const filmLabel = (id) => filmById[id].title + " · " + filmById[id].year;

  let scope = "all";
  const S = () => D.scopes[scope];

  /* ---------- odds ladder ---------- */
  function ladder() {
    const box = document.getElementById("ladder");
    box.innerHTML = "";
    const cap = D.config.record_horizon_mu;
    const top = S().scenes[0];
    const steps = [
      ["1 in 10", "1 MU"],
      ["1 in 1,000", "3 MU"],
      ["1 in a million", "6 MU"],
      ["1 in a trillion", fmt(cap) + " MU · cap"],
      [top.odds.replace("< ", ""), mu(top.central, top.lower_bound) + " MU"],
    ];
    steps.forEach(([odds, m]) => {
      const d = el("div");
      d.appendChild(el("span", "odds", odds));
      d.appendChild(el("span", "mu", m));
      box.appendChild(d);
    });
  }

  /* ---------- scenes ---------- */
  function worksheet(sceneId) {
    const ev = D.events[sceneId];
    const sheet = el("div", "sheet");
    const meta = S().rank_stability.scenes[sceneId];

    sheet.appendChild(el("h3", null, "What the film shows"));
    sheet.appendChild(el("p", null, ev.depicted));
    if (ev.inferred) {
      sheet.appendChild(el("h3", null, "Inferred, not shown"));
      sheet.appendChild(el("p", null, ev.inferred));
    }
    if (ev.in_universe_excuse) {
      sheet.appendChild(el("h3", null, "In-universe excuse (not credited)"));
      sheet.appendChild(el("p", null, ev.in_universe_excuse));
    }

    sheet.appendChild(el("h3", null, "Components, and why"));
    ev.components.forEach((c) => {
      const box = el("div", "comp");
      const head = el("div", "comp-head");
      const dot = el("span", "dot");
      dot.style.background = CATCOLOR[c.category];
      head.appendChild(dot);
      head.appendChild(el("span", "comp-claim", c.claim));
      head.appendChild(el("span", "tag", c.category));
      head.appendChild(el("span", "tag", EVIDENCE[c.evidence]));
      head.appendChild(
        el("span", "comp-mu", (c.capped ? "≥" : "") + fmt(c.mu.central) + " MU" + (c.capped ? " (cap)" : " (" + fmt(c.mu.low) + "–" + fmt(c.mu.high) + ")"))
      );
      box.appendChild(head);
      box.appendChild(el("p", "comp-why", c.reasoning));
      box.appendChild(el("p", "comp-why", "Dependence: " + c.dependence));
      const credits = c.credits.map((k) => D.characters[k.character].name + " (" + k.role + ")").join(", ");
      box.appendChild(el("p", "comp-why", "Credited: " + credits));
      if (c.references.length) {
        const refs = c.references.map((r) => {
          const ref = D.references[r];
          const numeric = typeof ref.value === "number";
          return ref.quantity + ": " + ref.value + (numeric ? " " + ref.unit : "");
        }).join(" · ");
        box.appendChild(el("p", "comp-why", "Real-world figures: " + refs));
      }
      sheet.appendChild(box);
    });

    sheet.appendChild(el("h3", null, "Confidence and gaps"));
    let gaps = "Confidence in this estimate: " + ev.confidence + ".";
    if (ev.visually_unverified.length) gaps += " Not verified on screen: " + ev.visually_unverified.join("; ") + ".";
    if (meta) gaps += " In 10,000 simulated draws it ranked #" + meta.median_rank + " most often.";
    sheet.appendChild(el("p", null, gaps));

    sheet.appendChild(el("h3", null, "Sources"));
    const srcs = el("p", "srcs");
    ev.plot_sources.forEach((sid) => {
      const s = D.sources[sid];
      if (s.url) {
        const a = el("a", null, s.title);
        a.href = s.url;
        a.rel = "noopener";
        srcs.appendChild(a);
      } else {
        srcs.appendChild(el("span", "tag", s.title));
      }
    });
    sheet.appendChild(srcs);
    return sheet;
  }

  function scenes() {
    const openId = new URLSearchParams(location.search).get("open");
    const box = document.getElementById("scenes");
    box.innerHTML = "";
    const list = S().scenes;
    const max = list[0].central;
    document.getElementById("scenes-note").textContent =
      list.length + " scored events. Bar length is linear in Magic Units, and Magic Units are already a log scale, so each full step is another ten-fold drop in the odds. “≥” marks a capped lower bound: a component that breaks a hard physical limit is held at " +
      fmt(D.config.record_horizon_mu) + " MU rather than given an invented number.";

    list.forEach((s, i) => {
      const row = el("button", "row");
      row.setAttribute("aria-expanded", "false");
      row.appendChild(el("span", "rank", String(i + 1).padStart(2, "0")));
      row.appendChild(el("span", "name", s.title));
      row.appendChild(el("span", "value", mu(s.central, s.lower_bound)));
      row.appendChild(el("span", "film", filmLabel(s.film) + " · " + s.odds));
      const track = el("span", "track");
      const fill = el("span", "fill");
      fill.style.width = Math.max(2, (s.central / max) * 100) + "%";
      track.appendChild(fill);
      row.appendChild(track);
      box.appendChild(row);

      let open = null;
      const toggle = () => {
        if (open) {
          open.remove();
          open = null;
          row.setAttribute("aria-expanded", "false");
          return;
        }
        open = worksheet(s.id);
        row.after(open);
        row.setAttribute("aria-expanded", "true");
      };
      row.addEventListener("click", toggle);
      if (openId && openId === s.id) toggle();
    });
  }

  /* ---------- characters ---------- */
  function characters() {
    const legend = document.getElementById("legend");
    legend.innerHTML = "";
    CATS.forEach((c) => {
      const s = el("span");
      const d = el("span", "dot");
      d.style.background = CATCOLOR[c];
      s.appendChild(d);
      s.appendChild(document.createTextNode(c));
      legend.appendChild(s);
    });

    const box = document.getElementById("chars");
    box.innerHTML = "";
    const eligible = S().characters.filter((c) => c.board_eligible);
    const max = Math.max.apply(null, eligible.map((c) => c.central));
    document.getElementById("chars-note").textContent =
      "Everyone in a stunt gets its full score, so these totals add up to more than the scene totals. They are an additive index of absurdity, not the probability of a life. A character needs " +
      D.config.board_min_events + " scored events and " + fmt(D.config.board_min_minutes) + " estimated minutes to be ranked.";

    eligible.forEach((c) => {
      const r = el("div", "cbar");
      r.appendChild(el("span", "cname", c.name));
      const stack = el("span", "stack");
      CATS.forEach((cat) => {
        const v = c.by_category[cat];
        if (v <= 0) return;
        const seg = el("span", "seg");
        seg.style.width = (v / max) * 100 + "%";
        seg.style.background = CATCOLOR[cat];
        seg.title = cat + " " + fmt(v) + " MU";
        stack.appendChild(seg);
      });
      r.appendChild(stack);
      r.appendChild(el("span", "ctot", mu(c.central, c.lower_bound)));
      box.appendChild(r);
    });

    const small = S().characters.filter((c) => !c.board_eligible).slice(0, 6);
    document.getElementById("chars-small").textContent =
      "Below the line, too little evidence to rank: " +
      small.map((c) => c.name + " (" + mu(c.central, c.lower_bound) + " MU, " + c.ineligible_reason + ")").join("; ") + ".";
  }

  /* ---------- rate ---------- */
  function rates() {
    const box = document.getElementById("rates");
    box.innerHTML = "";
    const eligible = S().characters.filter((c) => c.board_eligible && c.rate_per_100);
    eligible.sort((a, b) => b.rate_per_100.central - a.rate_per_100.central);
    const max = Math.max.apply(null, eligible.map((c) => c.rate_per_100.high));
    const st = S().rank_stability.rates;
    const leader = eligible[0];
    const p1 = st && st[leader.id] ? Math.round(st[leader.id].p_rank["1"] * 100) : null;
    document.getElementById("rate-note").textContent =
      "Screen time is estimated from scene-by-scene presence logs, not measured frame by frame, so treat these as a band rather than a number. " +
      (p1 !== null
        ? leader.name + " leads, but only in " + p1 + "% of 10,000 simulated draws once each character's screen-time error is included. Read the top of this board as a tie."
        : "");

    eligible.forEach((c) => {
      const r = el("div", "rate");
      r.appendChild(el("span", "cname", c.name));
      const range = el("span", "range");
      const w = el("span", "whisker");
      w.style.left = (c.rate_per_100.low / max) * 100 + "%";
      w.style.width = ((c.rate_per_100.high - c.rate_per_100.low) / max) * 100 + "%";
      range.appendChild(w);
      const pt = el("span", "pt");
      pt.style.left = (c.rate_per_100.central / max) * 100 + "%";
      range.appendChild(pt);
      r.appendChild(range);
      r.appendChild(el("span", "rval", fmt(c.rate_per_100.central) + " /100 min"));
      box.appendChild(r);
    });
  }

  /* ---------- films ---------- */
  function films() {
    const box = document.getElementById("films");
    box.innerHTML = "";
    const list = S().films;
    const max = Math.max.apply(null, list.map((f) => f.central));
    const worst = list.reduce((a, b) => (b.n_rejected > a.n_rejected ? b : a));
    document.getElementById("films-note").textContent =
      "Total Magic Units per film, in release order. The first four films sit near the ground. " +
      "Coverage is not even: " + worst.title + " had " + worst.n_rejected +
      " candidates screened out, most for want of a second source, so its total is a floor rather than a verdict.";

    list.forEach((f) => {
      const col = el("div", "fcol");
      col.appendChild(el("div", "fval", mu(f.central, f.lower_bound)));
      const bar = el("div", "fbar" + (f.spinoff ? " spin" : ""));
      bar.style.height = Math.max(3, (f.central / max) * 150) + "px";
      bar.title = f.title + ": " + fmt(f.central) + " MU across " + f.n_events + " events";
      col.appendChild(bar);
      col.appendChild(el("div", "flab", f.year));
      box.appendChild(col);
    });
  }

  /* ---------- method ---------- */
  function method() {
    const box = document.getElementById("method");
    box.innerHTML = "";
    const nEvents = Object.keys(D.events).length;
    const nComp = Object.values(D.events).reduce((a, e) => a + e.components.length, 0);
    const rows = [
      ["Scored events", nEvents, "One continuous attempt with one outcome, scoring " + fmt(D.config.event_threshold_mu) + " MU or more."],
      ["Components", nComp, "Separate failure modes inside those events. Each carries its own evidence type and reasoning."],
      ["Screened out", D.rejected.length, "Candidates considered and not scored: ordinary, below threshold, merged, or too thinly sourced."],
      ["Plot-armor items", D.plot_armor.length, "Resurrections, retcons and magic surveillance. Counted separately and never converted to Magic Units."],
      ["Cap", fmt(D.config.record_horizon_mu) + " MU", "One in a trillion, roughly one year of every car trip on Earth. A component that breaks a hard limit stops here."],
      ["Judgment cap", fmt(D.config.judgment_cap_mu) + " MU", "A component resting on judgment alone cannot exceed this, so guesswork cannot inflate a score."],
    ];
    const t = el("table");
    const tb = el("tbody");
    rows.forEach(([k, v, why]) => {
      const tr = el("tr");
      tr.appendChild(el("th", null, k));
      tr.appendChild(el("td", "num", String(v)));
      tr.appendChild(el("td", null, why));
      tb.appendChild(tr);
    });
    t.appendChild(tb);
    box.appendChild(t);

    const limits = [
      "Screen time is estimated, not measured, so the per-minute board is a band.",
      "Scenes with only one source are not scored at all, which holds some films below their true total.",
      "Character totals give full credit to everyone present, so they do not sum to the scene totals.",
      "Above the cap, scores are lower bounds. A bigger gap between two capped scenes is not a real difference.",
    ];
    box.appendChild(el("h3", null, "Known limits"));
    const ul = el("ul");
    limits.forEach((l) => ul.appendChild(el("li", null, l)));
    box.appendChild(ul);

    document.getElementById("foot-counts").textContent =
      nEvents + " scored events · " + nComp + " components · " + D.films.length + " films · " +
      D.rejected.length + " candidates screened out · simulation seed " + S().rank_stability.seed + ".";
  }

  /* ---------- social card routes ---------- */
  function card(kind) {
    document.body.classList.add("card", "card-" + kind);
    const f = document.getElementById("cardframe");
    f.setAttribute("aria-hidden", "false");
    const list = S().scenes;
    const top = list[0];
    const head = el("p", "doccode", "FF-MU-1 · REV A · " + Object.keys(D.events).length + " SCORED EVENTS");
    f.appendChild(head);

    if (kind === "og") {
      const h = el("h1", null, "The Fast & Furious Magic Index");
      f.appendChild(h);
      f.appendChild(el("div", "ogstat", mu(top.central, top.lower_bound) + " MU"));
      f.appendChild(el("p", "lede", top.title + " — " + filmLabel(top.film) + ". Odds worse than " + top.odds.replace("< ", "") + "."));
      const mini = el("div", "bd");
      list.slice(1, 4).forEach((s, i) => {
        const line = el("div");
        line.appendChild(el("span", null, String(i + 2).padStart(2, "0") + "  " + s.title));
        line.appendChild(el("span", "mu", mu(s.central, s.lower_bound) + " MU"));
        mini.appendChild(line);
      });
      f.appendChild(mini);
      const foot = el("div", "foot");
      foot.appendChild(el("span", null, "One Magic Unit = one order of magnitude of improbability"));
      foot.appendChild(el("span", null, "fast-furious.tonygwu.com"));
      f.appendChild(foot);
      return;
    }

    f.appendChild(el("h1", null, "The Fast & Furious Magic Index"));
    f.appendChild(el("p", "lede", "How impossible is each stunt? One Magic Unit is one order of magnitude of improbability. Bars run to " + fmt(top.central) + "."));
    const max = top.central;
    list.slice(0, 5).forEach((s, i) => {
      const row = el("div", "crow");
      row.appendChild(el("span", "rank", String(i + 1).padStart(2, "0")));
      const nm = el("span", "name", s.title);
      row.appendChild(nm);
      row.appendChild(el("span", "value", mu(s.central, s.lower_bound)));
      row.appendChild(el("span", "film", filmLabel(s.film)));
      const track = el("span", "track");
      const fill = el("span", "fill");
      fill.style.width = (s.central / max) * 100 + "%";
      track.appendChild(fill);
      row.appendChild(track);
      f.appendChild(row);
    });
    const axis = el("div", "axis");
    [["0 MU", "certain"], [fmt(D.config.record_horizon_mu) + " MU", "1 in a trillion · cap"], [fmt(max) + " MU", top.odds.replace("< ", "")]].forEach(([a, b]) => {
      const d = el("div");
      d.appendChild(el("b", null, a));
      d.appendChild(document.createTextNode(b));
      axis.appendChild(d);
    });
    f.appendChild(axis);

    const bd = el("div", "bd");
    bd.appendChild(el("p", "doccode", "WHY " + top.title.toUpperCase() + " SCORES " + fmt(top.central) + ": " + D.events[top.id].components.length + " SEPARATE IMPOSSIBILITIES"));
    D.events[top.id].components.forEach((c) => {
      const line = el("div");
      const dot = el("span", "dot");
      dot.style.background = CATCOLOR[c.category];
      line.appendChild(dot);
      line.appendChild(el("span", null, c.claim));
      line.appendChild(el("span", "mu", (c.capped ? "≥" : "") + fmt(c.mu.central) + " MU"));
      bd.appendChild(line);
    });
    f.appendChild(bd);

    const foot = el("div", "foot");
    foot.appendChild(el("span", null, D.films.length + " films · every component sourced · ≥ = capped lower bound"));
    foot.appendChild(el("span", null, "fast-furious.tonygwu.com"));
    f.appendChild(foot);
  }

  /* ---------- controls ---------- */
  function renderAll() {
    ladder();
    scenes();
    characters();
    rates();
    films();
    method();
  }

  function setScope(next) {
    scope = next;
    document.getElementById("scope-all").setAttribute("aria-pressed", String(next === "all"));
    document.getElementById("scope-saga").setAttribute("aria-pressed", String(next === "saga"));
    renderAll();
  }

  const params = new URLSearchParams(location.search);
  if (params.get("scope") === "saga") scope = "saga";
  if (params.get("theme") === "dark" || params.get("theme") === "light") {
    document.documentElement.setAttribute("data-theme", params.get("theme"));
  } else {
    try {
      const saved = localStorage.getItem("ffmu-theme");
      if (saved) document.documentElement.setAttribute("data-theme", saved);
    } catch (e) { /* private mode: fall back to the system setting */ }
  }

  if (params.get("debug") === "width") {
    document.title = "W " + window.innerWidth + " / scroll " + document.documentElement.scrollWidth +
      " / lede " + Math.round(document.querySelector(".lede").getBoundingClientRect().width);
  }

  const cardKind = params.get("card");
  if (cardKind === "main" || cardKind === "og") {
    card(cardKind);
  } else {
    document.getElementById("doccode").textContent =
      "FF-MU-1 · REV A · " + Object.keys(D.events).length + " SCORED EVENTS · " + D.films.length + " FILMS";
    document.getElementById("scope-all").addEventListener("click", () => setScope("all"));
    document.getElementById("scope-saga").addEventListener("click", () => setScope("saga"));
    const tbtn = document.getElementById("theme");
    const label = () => {
      const t = document.documentElement.getAttribute("data-theme");
      tbtn.textContent = "Theme: " + (t ? t : "auto");
      tbtn.setAttribute("aria-pressed", String(!!t));
    };
    tbtn.addEventListener("click", () => {
      const cur = document.documentElement.getAttribute("data-theme");
      const next = cur === "dark" ? "light" : cur === "light" ? "" : "dark";
      document.documentElement.setAttribute("data-theme", next);
      try { next ? localStorage.setItem("ffmu-theme", next) : localStorage.removeItem("ffmu-theme"); } catch (e) { /* ignore */ }
      label();
    });
    label();
    setScope(scope);
  }
})();
